config/routes.rb
Userbank::Application.routes.draw do
  
  resources :accounts
  resources :users
  resources :sessions, :only => [:new, :create, :destroy]

  match '/', :to => 'pages#home'
  match '/home', :to => 'pages#home'
  match '/about', :to => 'pages#about'
  match '/login', :to => 'pages#login'
  match '/help', :to => 'pages#help'
  match '/signup', :to => 'users#new'
  match '/signin', :to => 'sessions#new'
  match '/signout', :to => 'sessions#destroy'
  match '/newacct', :to => 'accounts#new'  
  match 'accounts/:id/deposit' => 'accounts#deposit'
  match 'accounts/:id/withdrawal' => 'accounts#withdrawal'
  match 'accounts/:id/transfer' => 'accounts#transfer'
  match 'accounts/:id/show2' => 'accounts#show2'
   
  root :to => 'pages#home'
  
  resources :accounts do 
     member do 
       get 'deposit'
       get 'withdrawal'
       get 'transfer'
       get 'show2'
     end
  end

  

end

app/views/pages/about.html.erb
The HW1 assignment is described here:
<br>
<%= link_to "https://moodle.brandeis.edu/file.php/11062/Assignments/homework1.htm", "https://moodle.brandeis.edu/file.php/11062/Assignments/homework1.htm" %>
<br>
<br>
The original incarnation of this assignment may be viewed at <%= link_to "this other site on Heroku", "http://morning-rain-796.heroku.com/" %>.  This version adds some of the extra credit options described there, including:
<br>
<ul>
<li>Separation of the User model from the Account model, letting each user have and create multiple accounts.</li>
<li>A hierarchy of users, where Administrative users are able to do more tasks and granted wider access in the system than Normal users.</li>
<li>A username/password login scheme demonstrating the use of a salt to avoid saving user passwords in the database, and the use of a cookie-based user session.</li>
<li>A signup page where users can create their own username/password combinations.</li>
</ul>
<br>
Note: the following open source projects were used in this project:
  <ul>
  <li><%= link_to "Ruby on Rails Tutorial", "http://railstutorial.org/ruby-on-rails-tutorial-book" %></li>
   <li><%= link_to "GitHub", "http://github.com" %></li>
   <li><%= link_to "Heroku", "http://heroku.com" %></li>
   <li><%= link_to "Blueprint CSS", "http://www.blueprintcss.org/" %></li>
  </ul>

app/views/pages/help.html.erb
<h1>Banking App</h1>
<p>
  This is the help page.
</p>

app/views/pages/home.html.erb
<h1>Banking App</h1>

<p>
  This is the home page.
</p>

<% if !signed_in? %>
<%= link_to "Sign up now!", signup_path, :class => "signup_button round" %>
<br>
<div align="center">Existing users may <%= link_to "sign in here.", signin_path %></div>
<% end %>

app/views/pages/login.html.erb
<h1>Banking App</h1>
<p>
  This is the login page.
</p>

app/views/pages/new.html.erb
<h1>Banking App</h1>
<p>
  This is the signup page.
</p>