config/routes.rb
Userbank::Application.routes.draw do
  
  resources :accounts
  resources :users
  resources :sessions, :only => [:new, :create, :destroy]

  match '/', :to => 'pages#home'
  match '/home', :to => 'pages#home'
  match '/about', :to => 'pages#about'
  match '/login', :to => 'pages#login'
  match '/help', :to => 'pages#help'
  match '/signup', :to => 'users#new'
  match '/signin', :to => 'sessions#new'
  match '/signout', :to => 'sessions#destroy'
  match '/newacct', :to => 'accounts#new'  
  match 'accounts/:id/deposit' => 'accounts#deposit'
  match 'accounts/:id/withdrawal' => 'accounts#withdrawal'
  match 'accounts/:id/transfer' => 'accounts#transfer'
  match 'accounts/:id/show2' => 'accounts#show2'
   
  root :to => 'pages#home'
  
  resources :accounts do 
     member do 
       get 'deposit'
       get 'withdrawal'
       get 'transfer'
       get 'show2'
     end
  end

  

end

app/views/layouts/_footer.html.erb
<footer>
  <% if signed_in? %>
  <nav class="round">  
    <ul>
      <% if current_user.admin? %>
      <li><%= link_to "All Users", users_path %></li>
      <li><%= link_to "All Accounts", accounts_path %></li>
      <% end %>
      <li><%= link_to "Profile", current_user %></li>
      <li><%= link_to "Open Account", newacct_path %></li>
    </ul>
  </nav>
  <% end %>
  <p>
  <nav class="round">
  This is a Ruby on Rails site built based on the <%= link_to "Ruby on Rails Tutorial", "http://railstutorial.org/ruby-on-rails-tutorial-book" %>. </nav>
</footer>

app/views/layouts/_header.html.erb
<header>
  <%= link_to logo, root_path %>
  <nav class="round">
    <ul>
      <li><%= link_to "Home", home_path %></li>
      <li><%= link_to "About", about_path %></li>
      <% if signed_in? %>
        <li><%= link_to current_user.fullname + " - Sign out", signout_path, :method => :delete %></li>
      <% else %>
      <li><%= link_to "Sign in", signin_path %></li>
      <% end %>
    </ul>
  </nav>
</header>

app/views/layouts/_stylesheets.html.erb
<!--[if lt IE 9]>
<script src="http://html5shiv.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->
<%= stylesheet_link_tag 'blueprint/screen', :media => 'screen' %>
<%= stylesheet_link_tag 'blueprint/print',  :media => 'print' %>
<!--[if lt IE 8]><%= stylesheet_link_tag 'blueprint/ie' %><![endif]-->
<%= stylesheet_link_tag 'custom', :media => 'screen' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= title %></title>
    <%= csrf_meta_tag %>
    <%= render 'layouts/stylesheets' %>
    <%= javascript_include_tag :defaults %>
  </head>
  <body>
    <div class="container">
      <%= render 'layouts/header' %>
      <section class="round">
        <% flash.each do |key, value| %>
          <div class="flash <%= key %>"><%= value %></div>
        <% end %>
        <%= yield %>
      </section>
      <%= render 'layouts/footer' %>
      <%= debug(params) if Rails.env.development? %>
    </div>
  </body>
</html>