config/routes.rb
Userbank::Application.routes.draw do
  
  resources :accounts
  resources :users
  resources :sessions, :only => [:new, :create, :destroy]

  match '/', :to => 'pages#home'
  match '/home', :to => 'pages#home'
  match '/about', :to => 'pages#about'
  match '/login', :to => 'pages#login'
  match '/help', :to => 'pages#help'
  match '/signup', :to => 'users#new'
  match '/signin', :to => 'sessions#new'
  match '/signout', :to => 'sessions#destroy'
  match '/newacct', :to => 'accounts#new'  
  match 'accounts/:id/deposit' => 'accounts#deposit'
  match 'accounts/:id/withdrawal' => 'accounts#withdrawal'
  match 'accounts/:id/transfer' => 'accounts#transfer'
  match 'accounts/:id/show2' => 'accounts#show2'
   
  root :to => 'pages#home'
  
  resources :accounts do 
     member do 
       get 'deposit'
       get 'withdrawal'
       get 'transfer'
       get 'show2'
     end
  end

  

end

app/models/account.rb
# == Schema Information
# Schema version: 20110401004449
#
# Table name: accounts
#
#  id           :integer         not null, primary key
#  amount       :decimal(, )
#  interestrate :decimal(, )
#  user_id      :integer
#  created_at   :datetime
#  updated_at   :datetime
#  acct_type    :string(255)
#

class Account < ActiveRecord::Base
  # needed for number_to_currency method
  include ActionView::Helpers::NumberHelper

  belongs_to :user
  attr_accessible :amount, :acct_type, :interestrate, :user_id
  
  validates :amount, :presence => true,
                     :numericality => { :greater_than => 0 }
  validates :user_id, :presence => true
  validates :acct_type, :presence => true
  validates :interestrate, :presence => true


  default_scope :order => 'accounts.id ASC'
  
  def deposit (amount) 
    self.update_attributes(:amount => self.amount + amount)
  end
  
  def withdraw (amount) 
    self.update_attributes(:amount => self.amount - amount)
  end  

  def full_name_with_num_and_amt
    self.id.to_s + " - " + User.find(self.user_id).fullname + " - " + number_to_currency(self.amount, :unit => "$")
  end
end

app/controllers/accounts_controller.rb
class AccountsController < ApplicationController
  # needed for number_to_currency method
  include ActionView::Helpers::NumberHelper

  before_filter :authenticate
  before_filter :okay_user, :except => [:index, :new, :create]
  before_filter :admin_user, :only => :index

  # GET /accounts
  # GET /accounts.xml
  def index
    @accounts = Account.paginate(:page => params[:page], :per_page => 10)

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @accounts }
    end
  end

  # GET /accounts/1
  # GET /accounts/1.xml
  def show
    @account = Account.find(params[:id])
    @user = User.find(@account.user_id)
    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @account }
    end
  end

  # GET /accounts/new
  # GET /accounts/new.xml
  def new
    @account = Account.new
    
    if current_user.admin? 
      @user_choices = User.all
    else
      @user_choices = [current_user]
    end
    
    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @account }
    end

  end

  # GET /accounts/1/edit
  def edit
    @account = Account.find(params[:id])
    
    if current_user.admin? 
      @user_choices = User.all
    else
      @user_choices = [current_user]
    end
  end

  # POST /accounts
  # POST /accounts.xml
  def create
    @account = Account.new(params[:account])

    respond_to do |format|
      if @account.save
        format.html { redirect_to(@account, :notice => 'Account was successfully created.') }
        format.xml  { render :xml => @account, :status => :created, :location => @account }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @account.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /accounts/1
  # PUT /accounts/1.xml
  def update
    @account = Account.find(params[:id])

    respond_to do |format|
      if @account.update_attributes(params[:account])
        format.html { redirect_to(@account, :notice => 'Account was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @account.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /accounts/1
  # PUT /accounts/1.xml
  def deposit
    @account = Account.find(params[:id])

    respond_to do |format|
      if (amount = params[:dep_amount])
        amount = amount.to_f
        @account.deposit(amount)
        format.html { redirect_to(@account, :notice => "Account #{@account.id} was successfully updated.") }
        format.xml  { head :ok }
      else
        format.html { render :action => "deposit" }
        format.xml  { render :xml => @account.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /accounts/1
  # PUT /accounts/1.xml
  def withdrawal
    @account = Account.find(params[:id])

    respond_to do |format|
      if (amount = params[:withd_amount])
        amount = amount.to_f
        if (amount <= @account.amount)
           @account.withdraw(amount)
           format.html { redirect_to(@account, :notice => "Account #{@account.id} was successfully updated.") }
           format.xml  { head :ok }
        else
           @error = "Amount may not exceed the account balance."
           format.html { render :action => "withdrawal" }
           format.xml  { render :xml => @account.errors, :status => :unprocessable_entity }
        end
      else
        format.html { render :action => "withdrawal" }
        format.xml  { render :xml => @account.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /accounts/1
  # PUT /accounts/1.xml
  def transfer
    # Transfer from account1
    @account1 = Account.find(params[:id])
    @user1 = User.find(@account1.user_id)
    # A temp array for the options menu
    #  If it's a normal user, list all user's accounts except account1
    #  If it's an admin user, list all accounts except account1
    if admin_user 
      @not_account1 = Account.all.reject{|x| x == @account1 }
    else
      @not_account1 = @user1.accounts.reject{|x| x == @account1 }
    end

    respond_to do |format|
      if (amount = params[:transfer_amount])
        @account2 = Account.find(params[:account2_id])
        amount = amount.to_f
        @account1.withdraw(amount)
        @account2.deposit(amount)
        amount = number_to_currency(amount, :unit => "$")
        @notice = amount + " was successfully transferred from account " + @account1.id.to_s + " to account " + @account2.id.to_s + "."
        @user2 = User.find(@account2.user_id)
        format.html { render (:action => "show2") }
        format.xml  { head :ok }
      else
        format.html { render :action => "transfer" }
        format.xml  { render :xml => @account.errors, :status => :unprocessable_entity }
      end
    end
  end

  def show2
     #@account1 = Account.find(params[:id])
     #@account2 = Account.find(params[:account2_id])
     respond_to do |format|
      format.html # show2.html.erb
    end
  end

  # DELETE /accounts/1
  # DELETE /accounts/1.xml
  def destroy
    @account = Account.find(params[:id])
    @account.destroy

    respond_to do |format|
      format.html { redirect_to(accounts_url) }
      format.xml  { head :ok }
    end
  end
  
  
  private

    def authenticate
      deny_access unless signed_in?
    end
    
    def okay_user
      if current_user.admin?
      else 
        @user = User.find(Account.find(params[:id]).user_id)
        redirect_to(root_path) unless current_user?(@user)
      end
    end
    
    def admin_user
      deny_access unless current_user.admin?
    end
    
end

app/helpers/accounts_helper.rb
module AccountsHelper
end

app/views/accounts/_account.html.erb
<tr>
<td><%= account.id %></td>
<td><%= account.acct_type %></td>
<td><%= number_to_currency(account.amount, :unit => "$") %></td>
<td><%= link_to 'Deposit', deposit_account_path(account) %>
<td><%= link_to 'Withdraw', withdrawal_account_path(account) %>
<% if current_user.accounts.length < 2 %>
<td></td>
<% else %>
<td><%= link_to 'Transfer', transfer_account_path(account) %>
<% end %>
</tr>

app/views/accounts/_dep_form.html.erb
<% form_tag(:action => 'deposit', :method=>'post') do %>
  <% if @error %>
    <div id="error_explanation">
      <ul>
        <li><%= @error %></li>
      </ul>
    </div>
  <% end %>

  <div class="field">
    Amount:
    <%= number_field_tag "dep_amount", nil, :min => 0.01 ,:max => @account.amount %>
  </div>
  <div class="actions">
    <%= submit_tag "Deposit" %>
  </div>
<% end %>

app/views/accounts/_form.html.erb
<script type="text/javascript">

  function setinterestrate(choice){ 
    var rates=[0.02,0.05];
    var p=choice.options.selectedIndex;
    choice.form.elements['account[interestrate]'].value=rates[p];
  } 
</script>

<%= form_for(@account) do |f| %>
  <% if @account.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@account.errors.count, "error") %> prohibited this account from being saved:</h2>

      <ul>
      <% @account.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <label for="account_user_id">User</label><br />
    <%= collection_select(:user, :id, @user_choices, :id, 
                          :fullname, {}, :name => "account[user_id]") %>
  </div>
  <div class="field">
    <label for="account_acct_type">Account Type</label><br />
    <select name="account[acct_type]" onload=setinterestrate(this) onchange=setinterestrate(this)>
    <option value="Checking">Checking</option>
    <option value="Savings">Savings</option>
    </select>
  </div>
  <div class="field">
    <%= f.label :amount %><br />
    <%= f.text_field :amount %>
  </div>
  <input name="account[interestrate]" type="hidden" value=0.02>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/accounts/_transfer_form.html.erb
<% form_tag(:action => 'transfer', :method=>'post') do %>
  <div class="field">
    To account: 
    
    <%= collection_select(:account, :id, @not_account1, :id, 
                          :full_name_with_num_and_amt, {}, :name => "account2_id") %>
  <div>
    
  <div class="field">
    Amount:  <%= number_field_tag "transfer_amount", nil, :min => 0.01 %>
  </div>

  <br />

  <div class="actions">
    <%= submit_tag "Transfer" %>
  </div>

<% end %>

app/views/accounts/_withd_form.html.erb
<% form_tag(:action => 'withdrawal', :method=>'post') do %>
  <% if @account.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@account.errors.count, "error") %> prohibited this account from being saved:</h2>

      <ul>
      <% @account.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <% if @error %>
    <div id="error_explanation">
      <ul>
        <li><%= @error %></li>
      </ul>
    </div>
  <% end %>

  <div class="field">
    Amount:
    <%= number_field_tag "withd_amount", nil, :min => 0.01 ,:max => @account.amount %>
  </div>
  <div class="actions">
    <%= submit_tag "Withdraw" %>
  </div>
<% end %>

app/views/accounts/deposit.html.erb
<h1>Deposit into account <%= @account.id %></h1>
<h3>Current amount <%= number_to_currency(@account.amount, :unit => "$") %></h3>

<%= render 'dep_form' %>
<br>
<%= link_to "Cancel", user_path(@account.user_id) %>

app/views/accounts/edit.html.erb
<h1>Editing account</h1>

<%= render 'form' %>

<%= link_to 'Show', @account %> |
<%= link_to 'Back', accounts_path %>

app/views/accounts/index.html.erb
<h1>Listing accounts</h1>


<%= will_paginate %>

<table>
  <tr>
    <th>User</th>
    <th>ID</th>
    <th>Amount</th>
    <th>Type</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @accounts.each do |account| %>
  <tr>
<td><%= User.find(account.user_id).fullname %></td>
<td><%= account.id %></td>
<td><%= number_to_currency(account.amount, :unit => "$") %></td>
<td><%= account.acct_type %></td>
    <td><%= link_to 'Deposit', deposit_account_path(account) %>
    <td><%= link_to 'Withdraw', withdrawal_account_path(account) %>
    <td><%= link_to 'Transfer', transfer_account_path(account) %>    
</tr>
<% end %>
</table>

<br />


<%= will_paginate %>

<%= link_to 'New Account', new_account_path %>

app/views/accounts/new.html.erb
<h1>New account</h1>

<%= render 'form' %>

<br>
<%= link_to 'Back', accounts_path %>

app/views/accounts/show.html.erb
<h1>Account <%= @account.id %> for <%= @user.fullname %>:</h1>

<p id="notice"><%= notice %></p>

<p>
  <b>Account Type:</b>
  <%= @account.acct_type %>
</p>

<p>
  <b>Amount:</b>
  <%= number_to_currency(@account.amount, :unit => "$") %>
</p>

<p>
  <b>Interest Rate:</b>
  <%= @account.interestrate %>
</p>

<%= link_to 'Back', user_path(@account.user_id) %>

app/views/accounts/show2.html.erb
<p id="notice"><%= @notice %></p>

<table>

<tr>
<td><b>Name:</b></td>
<td><%= @user1.fullname %></td>
<td><%= @user2.fullname %></td>
</tr>

<tr>
<td><b>Account Number:</b></td>
<td><%= @account1.id %></td>
<td><%= @account2.id %></td>
</tr>

<tr>
<td><b>Amount:</b></td>
<td><%= number_to_currency(@account1.amount, :unit => "$") %></td>
<td><%= number_to_currency(@account2.amount, :unit => "$") %></td>
</tr>

</table>

app/views/accounts/transfer.html.erb
<h1>Transfer from account <%= @account1.id %></h1>
<h3>Current amount <%= number_to_currency(@account1.amount, :unit => "$") %></h3>

<%= render 'transfer_form' %>
<br><br>
<%= link_to "Cancel", user_path(@account1.user_id) %>

app/views/accounts/withdrawal.html.erb
<h1>Withdraw from account <%= @account.id %></h1>
<h3>Current amount <%= number_to_currency(@account.amount, :unit => "$") %></h3>

<%= render 'withd_form' %>
<br><br>
<%= link_to "Cancel", user_path(@account.user_id) %>